#!/usr/bin/perl

# $Id$

# Generate repeating events in a format suitable for converting to Palm 
# datebook .dba format with convdb
#
# Author: Richard Jones, April 2006

use strict;
use Getopt::Long;
use vars qw($opt_h);
use Date::Calc qw(Add_Delta_Days);
use Date::Manip qw(ParseDate UnixDate);

my $DEFAULT_LABEL = 'UKC Week';
my $label = $DEFAULT_LABEL;
my $DEFAULT_PERIOD = 7;
my $period = $DEFAULT_PERIOD;
my $DEFAULT_NUMBER = 1;
my $number = $DEFAULT_NUMBER;

my $usage = 'events.pl [-h] [-l label] [-p period] [-s start] day/month/year repeat...';

GetOptions("h"     => \$opt_h,
           "l=s"   => \$label,
           "p=i"   => \$period,
           "s=i"   => \$number,
            );
if($opt_h) {
  help($usage);
  exit 0;
}
die "Bad period $period.\n$usage" unless $period > 0;
#print Dumper(@ARGV);
die "Bad number of arguments $#ARGV.\n$usage" if ($ARGV % 2 != 0);


Date::Manip::Date_Init("Language=English","DateFormat=".$ENV{TZ});
print "#Repeated dates generated by event.pl\n";
printf "%s\t%s\t%s\t%s\t%s\n", '%d/%m/%y', '%h:%i', '%t', '%u', '%v';

while ($#ARGV > 0) {
  my $arg = shift;
  my $date = ParseDate($arg);
  #print Dumper($date);
  die "$arg is a bad date.\n$usage" unless $date;
  my ($year, $month, $day) = UnixDate($date, "%Y", "%m", "%d");
  
  my $repeat = shift;
  die "Bad repeat $repeat.\n$usage" unless $repeat > 0;

  for (my $i = 0; $i < $repeat; $i++) {
    printf "%s/%s/%s\t09:00\t1\tY\t%s\n", $day,$month,$year, "$label $number";
    ($year, $month, $day) = Add_Delta_Days($year, $month, $day, $period);
    $number++;
  }
}

# 
# Print help message
#
sub help($) {
my $usage = shift;
  print <<"EOT"
$usage
events.pl expects groups of 2 arguments. It will generate a list of dates for
each group, starting with the date given and repeated repeat times.
Options:
  -h	    Print this message and exit.
  -l label  Print each event as "label N" where N is the number of the event.
            Default: $DEFAULT_LABEL.
  -p period The repeat period. Default: $DEFAULT_PERIOD;
  -s start  The starting number for the label. Default: $DEFAULT_NUMBER.
EOT
}
